const mealsData = {
  1: [
    {
      id: 1232,
      name: 'Chicken Breast - Cooked',
      completed: false,
      nutrition: {
        calories: 23,
        protein: 43,
        carbohydrates: {
          total: 34,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 12,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'tyson',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
    {
      id: 1232,
      name: 'Chicken Breast - Cooked',
      completed: false,
      nutrition: {
        calories: 23,
        protein: 43,
        carbohydrates: {
          total: 34,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 12,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'tyson',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
    {
      id: 1232,
      name: 'Chicken Breast - Cooked',
      completed: false,
      nutrition: {
        calories: 23,
        protein: 43,
        carbohydrates: {
          total: 34,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 12,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'tyson',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
    {
      id: 0,
      name: 'double double',
      nutrition: {
        calories: 23,
        protein: 50,
        carbohydrates: {
          total: 0,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 0,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'In-n-out',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
  ],
  2: [
    {
      id: 1232,
      name: 'Chicken Breast - Cooked',
      completed: false,
      nutrition: {
        calories: 23,
        protein: 43,
        carbohydrates: {
          total: 34,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 12,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'tyson',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
    {
      id: 0,
      name: 'double double',
      nutrition: {
        calories: 23,
        protein: 40,
        carbohydrates: {
          total: 0,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 0,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'In-n-out',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
  ],
  3: [
    {
      id: 1232,
      name: 'Chicken Breast - Cooked',
      completed: false,
      nutrition: {
        calories: 23,
        protein: 43,
        carbohydrates: {
          total: 34,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 12,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'tyson',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
    {
      id: 0,
      name: 'double double',
      nutrition: {
        calories: 23,
        protein: 0,
        carbohydrates: {
          total: 0,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 0,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'In-n-out',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
  ],
  4: [
    {
      id: 1232,
      name: 'Chicken Breast - Cooked',
      completed: false,
      nutrition: {
        calories: 23,
        protein: 43,
        carbohydrates: {
          total: 34,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 12,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'tyson',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
    {
      id: 0,
      name: 'double double',
      nutrition: {
        calories: 23,
        protein: 0,
        carbohydrates: {
          total: 0,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 0,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'In-n-out',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
  ],
  5: [
    {
      id: 1232,
      name: 'Chicken Breast - Cooked',
      completed: false,
      nutrition: {
        calories: 23,
        protein: 43,
        carbohydrates: {
          total: 34,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 12,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'tyson',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
    {
      id: 0,
      name: 'double double',
      nutrition: {
        calories: 23,
        protein: 0,
        carbohydrates: {
          total: 0,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 0,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'In-n-out',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
  ],
  6: [
    {
      id: 1232,
      name: 'Chicken Breast - Cooked',
      completed: false,
      nutrition: {
        calories: 23,
        protein: 43,
        carbohydrates: {
          total: 34,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 12,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'tyson',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
    {
      id: 0,
      name: 'double double',
      nutrition: {
        calories: 23,
        protein: 0,
        carbohydrates: {
          total: 0,
          fiber: 0,
          sugar: 0,
        },
        fats: {
          total: 0,
          saturated: 0,
          polyunsaturated: 0,
          monounsaturated: 0,
          trans: 0,
        },
        cholesterol: 0,
        sodium: 0,
        potassium: 0,
        vitaminA: 0,
        vitaminC: 0,
        calcium: 0,
        iron: 0,
      },
      brand: {
        name: 'In-n-out',
      },
      description: '',
      serving: {
        size: {},
      },
      buy: {},
    },
  ],
};

export default mealsData;
